### ISSUE TITLE
Add boat simulator ROS parameters

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/boat_simulator#37]
### Purpose

We want to be able to parameterize particular aspects of the boat simulator to allow other members to configure the simulator to test specific scenarios. In particular, we want to parameterize for the physics engine and the low level control module.

We want to hopefully get most of the parameters that we can foresee in this issue, but down the line we will probably gradually add more. The idea is to add most of the infrastructure in this issue!

### Description

You will likely need to make a PR both for the boat simulator when reading the parameters and for sailbot workspace when adding variables to the config file.

#### Parameters

We have the following ROS parameters that we want to put inside the configuration file:

```yaml
/**:
 logging_throttle_period_sec: 2.0

physics_engine_node:
 wind_sensor:
  generator_type: gaussian # One of "gaussian", "constant"
  gaussian_params:
   mean: [1.0, 0.0]
   stddev: [0.1, 0.1] # Standard deviation for x and y components
   corr_xy: 0.0
  constant_params:
   value: [1.0, 0.0]

low_level_control_node:
 rudder:
  disable_actuation: false
  fixed_angle_deg: 0.0 # Only used if rudder actuation is disabled
  actuation_request_period_sec: 10.0
  actuation_execution_period_sec: 0.5
  pid: # Only used if rudder actuation is enabled
   kp: 0.0
   ki: 0.0
   kd: 0.0
   buffer_size: 50
 wingsail:
  disable_actuation: false
  fixed_angle_deg: 0.0 # Only used if actuation is disabled
  actuation_request_period_sec: 10.0
  actuation_execution_period_sec: 0.5
  actuation_speed_deg_per_sec: 0.1 # Only used if actuation is enabled
 
```

#### Testing

All we care about for this issue is that the parameters are loaded into their respective ROS nodes by examining the debug logs.

### Resources

- [ROS Parameters](https://docs.ros.org/en/humble/Concepts/Basic/About-Parameters.html)
- [ROS Launch Files](https://ubcsailbot.github.io/docs/main/current/sailbot_workspace/launch_files/)
